### ISSUE TITLE
Long image can not show in full screen on Android.

### ISSUE THREAD

**Issue by zhaoyanxiang** [archriss/react-native-render-html#404] opened 2020-09-03 06:52 UTC
### Oath

I swear that I have completed these tasks before submitting:

- [√ ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [√ ] I have read the documentation here: https://git.io/JJcAl 
- [√ ] I have confirmed that this bug has not been reported yet

### Decision table

- [ √] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [√ ] My issue does not look like “The HTML element `<yyy>` is not rendered”

##### React Native

```
<HTML imagesMaxWidth={411} html={'<img src="https://images.xueyue.com.cn/upload/course/20200516/b4b0089653f1e9efb49623b92e5935f5.jpg"/>'} />

```
My phone's width is 411. The picture's original size is 751x4876.
But I can't show this picture in full screen.

##### Libraries

- react-native-render-html:
- react-native-webview:

#### Devices

- Samsung Galaxy S20+

**Comment by Allonsy-Jays** [comment] 2020-09-09 10:12
same issue +1

**Comment by jsamr** [comment] 2020-09-20 18:39
This issue probably has nothing to do with this library, but related to flex layout in React Native instead. If you have a ScrollView contentContainerStyle that looks like:

```js
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```
it will mess up the content, because `flex: 1` also sets `flexShrink` to `1`.
Use this instead:
```js
const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
  },
});
```
And
```js
function MyComponent() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <HTML
        html={
          '<img src="https://images.xueyue.com.cn/upload/course/20200516/b4b0089653f1e9efb49623b92e5935f5.jpg"/>'
        }
      />
    </ScrollView>
  );
}
```
It works for me!
See also https://stackoverflow.com/q/43143258/2779871
I'm closing, but if you still having an issue, fill free to reply.

**Closed by jsamr** 2020-09-20 18:39 UTC
Labels: bug, is:waiting for feedback

**Comment by Allonsy-Jays** [comment] 2020-09-21 05:20
> This issue probably has nothing to do with this library, but related to flex layout in React Native instead. If you have a ScrollView contentContainerStyle that looks like:
> 
> ```js
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>   },
> });
> ```
> 
> it will mess up the content, because `flex: 1` also sets `flexShrink` to `1`.
> Use this instead:
> 
> ```js
> const styles = StyleSheet.create({
>   container: {
>     flexGrow: 1,
>   },
> });
> ```
> 
> And
> 
> ```js
> function MyComponent() {
>   return (
>     <ScrollView contentContainerStyle={styles.container}>
>       <HTML
>         html={
>           '<img src="https://images.xueyue.com.cn/upload/course/20200516/b4b0089653f1e9efb49623b92e5935f5.jpg"/>'
>         }
>       />
>     </ScrollView>
>   );
> }
> ```
> 
> It works for me!
> See also https://stackoverflow.com/q/43143258/2779871
> I'm closing, but if you still having an issue, fill free to reply.

still same. i think it's problem because android image library, because IOS is really can show really good resolute image.

**Comment by jsamr** [comment] 2020-09-21 08:15
@Allonsy-Jays Can you share a full reproduction so I can help you?

**Comment by gnattu** [comment] 2021-04-21 14:02
I'm facing this as well. Want to let a long image to take the __FULL WIDTH__ of the screen, but the image ends up only takes a very small potion of screen width and not responding to width setting on tagStyles

**Comment by gnattu** [comment] 2021-04-21 14:15
Looks like the size calculation is having some problem by looking at `imageBoxDimensions` passed to `renderImage`

on iOS, the images has their sized calculated right and width equals to screen width:

```
 LOG  {"height": 7606.593137254902, "width": 390}
 LOG  {"height": 8144.06015037594, "width": 390}
```

However, on Android, we are getting a ridiculously low width:

```
ReactNativeJS: { width: 77, height: 1562 }
ReactNativeJS: { width: 75, height: 1504 }
```

Same image, same props. I'm wondering what caused this.

**Comment by gnattu** [comment] 2021-04-21 14:36
Looks like the method `fetchPhysicalImageDimensions ` is not getting the correct size of the image, hence the wrong rendering: 

```
'fetchPhysicalImageDimensions', 92, 1427
```

**Comment by gnattu** [comment] 2021-04-21 17:51
The root cause is that FaceBook's fresco library actively downsamples the images which is considered "too big", and returns the down sampled size. Even though you managed to set the correct size, react native's image component will render that downsampled version which will be very blurry. Solving this is out of the scope of this lib as it would be very complicated.

**Comment by jsamr** [comment] 2021-04-21 17:54
@gnattu Thank you for your thorough investigation. Indeed, that looks like an upstream limitation; worth adding a note regarding this issue in the help section!

**Comment by Bruce-Ming** [comment] 2021-10-10 02:44
> @gnattu Thank you for your thorough investigation. Indeed, that looks like an upstream limitation; worth adding a note regarding this issue in the help section!

Yes, this is the problem with react native Image components, react native FastImage is fine and I found that this library renders images using Image, so how do I replace Image with FastImage. i just saw some examples of custom renderers, but I didn't find how to replace

**Comment by jsamr** [comment] 2021-10-10 09:11
@Bruce-Ming https://meliorence.github.io/react-native-render-html/docs/content/images#by-reusing-internal-building-blocks ; just replace `IMGElementContentSuccess` with your FastImage-based component.

**Comment by Bruce-Ming** [comment] 2021-10-10 09:24
> IMGElementContentSuccess

Yes, I understand, but how do you go about replacing it? Can you be more specific, please?

**Comment by Bruce-Ming** [comment] 2021-10-10 09:25
> @Bruce-Ming https://meliorence.github.io/react-native-render-html/docs/content/images#by-reusing-internal-building-blocks ; just replace `IMGElementContentSuccess` with your FastImage-based component.

Yes, I understand, but how do you go about replacing it? Can you be more specific, please?
