### ISSUE TITLE
Some styles don't work

### ISSUE THREAD

**Issue by catmans1** [archriss/react-native-render-html#321] opened 2019-12-17 00:36 UTC
### Is this a bug report or a feature request?
This is maybe a bug

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?
I have.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?
I have
### Have you made sure that your issue hasn't already been reported/solved?
Sure.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
I just test on Android.

### Is the bug reproductible in a production environment (not a debug one)?
I test on Staging and Production environment

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?
Give example code and change the body

### Environment
Staging and Production

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. Following example code and change another body
2.
```
<p>My mother has <span style="color:blue;font-weight:bold">blue</span> eyes and my father has <span style="color:#fff;font-weight:bold;background-color:red;padding:2px 4px 2px 4px;border-radius: 2px">dark green</span> eyes.</p>
```
3.

### Expected Behavior

It will show like as:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_span

### Actual Behavior
It does not the same on website

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by jsamr** [comment] 2020-07-04 20:35
@catmans1 The set of accepted CSS rules is defined by `allowedStyles` and `ignoredStyles`. I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) which require reproducible demo. Feel free to post a new compliant issue.

**Closed by jsamr** 2020-07-04 20:35 UTC

**Comment by jsamr** [comment] 2020-07-05 12:20
@catmans1 We will fix this issue with inline CSS in next release. Stay tuned!
