### ISSUE TITLE
WebView is depreciated

### ISSUE THREAD

**Issue by presencewebdesign** [archriss/react-native-render-html#304] opened 2019-10-14 13:29 UTC
WebView will not work with version RN 0.61.0

Update the following file 
/node_modules/react-native-render-html/src/HTMLRenderers.js

Add this 
import { WebView } from 'react-native-webview'; 

And remove WebView from this line 
import { TouchableOpacity, Text, View, **WebView**, Platform } from 'react-native';

PS: when will this be updated?

**Comment by Utkarshkataria** [comment] 2019-10-15 07:15
It worked.. Thanks.

**Comment by mtnptrsn** [comment] 2019-10-23 08:37
This is already fixed in master, the issue is that it hasn't yet been released. When can we expect another release?

**Comment by maicolsantos** [comment] 2019-11-04 18:04
When are you planning to launch release?

**Comment by vomchik** [comment] 2019-11-05 08:50
@ThomasHenrissat  Could you please release a new version? 🙏

**Comment by ThomasHenrissat** [comment] 2019-11-05 09:00
Sorry I'm not in charge of this repo, please use the master branch for now.

**Comment by vomchik** [comment] 2019-11-05 09:04
i see, thanks

**Comment by jsamr** [comment] 2020-07-04 20:55
I am closing because this issue has been resolved in a recent release.

**Closed by jsamr** 2020-07-04 20:55 UTC
