### ISSUE TITLE
Display Math Functions to the Custom Renderer Method

### ISSUE THREAD

**Issue by shivamtagline** [archriss/react-native-render-html#416] opened 2020-10-17 09:49 UTC
Hello,
I am using your library for rendering html content.
I tried to display Math functions which are in <span> tag.
I have reviewed one of your issue, I tried with **react-native-math-view** but could not be able to use custom renderers to render math function.

Ref links:
1. https://github.com/archriss/react-native-render-html/issues/406
2. https://www.npmjs.com/package/react-native-math-view

respones:
<span class="math-tex">\(x = {-b \pm \sqrt{b^2-4ac} \over 2a}\)</span>

From the iOS working well but from android side I received this type of error. Please help me to solve this issue.
Here I have attached two ref screenshots,
iOS
![image](https://user-images.githubusercontent.com/52451946/96334188-6a4f9b80-108c-11eb-8652-58ebada8b79f.png)

Android
![image](https://user-images.githubusercontent.com/52451946/96334032-40e24000-108b-11eb-9659-fdc456b96205.png)

Please review.
Looking forward to your response,
Thanks.

**Comment by jsamr** [comment] 2020-10-17 10:10
@shivamtagline It looks like you are wrapping the latex content with a Text, which you cannot on some older React Native releases. That's just a guess since you have not provided source code, nor given the version used for this library and React Native. Please provide a reproduction and I'll be happy to help. [You are highly encouraged to follow our contribution guidelines for best feedback](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc). I am closing now because of miscompliance with those guidelines, but you can of course still post and I'll respond.

**Closed by jsamr** 2020-10-17 10:10 UTC
Labels: is:missing reproduction, is:missing template
