### ISSUE TITLE
Images not showing up and sometimes disappear

### ISSUE THREAD

**Issue by Krypternite** [archriss/react-native-render-html#333] opened 2020-01-01 13:04 UTC
### Is this a bug report or a feature request?

Bug Report

### Environment

  Environment:
    React: 16.9
    React native: 0.61.5
    react-native-render-html: 4.2.0

  Target Platform:
    iOS (10.3)

With React Native 0.61.5 and iOS 13, the images in the html sometimes do not show up at all and sometimes if they do, they disappear after a moment is the focus changes from the view.

![image](https://user-images.githubusercontent.com/9376390/71641643-9c426d80-2cc5-11ea-8add-ebed8bc74ac5.png)

**Comment by jsamr** [comment] 2020-07-04 20:27
@Krypternite Are you still facing this issue?

**Comment by jsamr** [comment] 2020-07-05 13:29
I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md). We are working on our free time and need a full reproduction to investigate. You are welcomed to post a new compliant issue.

**Closed by jsamr** 2020-07-05 13:29 UTC
Labels: bug, missing-template, waiting for feedback
