### ISSUE TITLE
No soup for you at the bottom content 

### ISSUE THREAD

**Issue by workhub90** [archriss/react-native-render-html#411] opened 2020-09-24 07:30 UTC
How to Remove this !

No Soup For you at bottom content

Libraries
react-native-render-html: @4.2.4-beta.1
react-native-webview: 10.9.0
Devices
Device 1 emulator (Google Pixel 3a)
OS: Android 9.0
Diagnostic:
Environment:
Device 2 simulator (iPhone 11 pro max)
OS: iOS 13.0
Diagnostic:
Environment:
Reproduction
Here the code i used show content
import HTML from 'react-native-render-html';

<-----CODE------>

content() {
return (

<HTML
html={this.props.article.description}
baseFontStyle={styles.textContent}
onLinkPress={(event, href) => this.props.openLink(href)}
>

{this.props.article.permalink_source != null && (

<TouchableOpacity
style={styles.btnOriginalSource}
onPress={() =>
this.props.toSource(this.props.article.permalink_source)
}>
Artikel Asli

)}

);
}

here the code for render html video embeded

<-----CODE------>

<p><span style="font-weight: 400;"><iframe src="//www.youtube.com/embed/euc-ClEXhuQ?t=2s" width="560" height="314" allowfullscreen="allowfullscreen"></iframe></span></p>

<-----CODE---->

the default shown video embeded youtube like this here  :
![Screenshot_1600930294](https://user-images.githubusercontent.com/56101357/94111379-293de000-fe6e-11ea-8c4b-7975ab4a0629.png)

yeah, the content video embeded youtube not full entire wide screen.

then, when i modified
here the code html while rendered content.
<----CODE---->

 [https://justpaste.it/36cbv](url)

<---CODE---->

yeah, the content video embeded youtube got full entire wide screen.
here the screenshoot :

![Screenshot_1600932470](https://user-images.githubusercontent.com/56101357/94114242-45438080-fe72-11ea-803a-9840aafedfab.png)
![Screenshot_1600932452](https://user-images.githubusercontent.com/56101357/94114265-4c6a8e80-fe72-11ea-9292-c822be7f701a.png)

but all of that. still showing this.
![Screenshot_1600762926](https://user-images.githubusercontent.com/56101357/94114337-6ad08a00-fe72-11ea-817e-ff6d236d84ba.png)

please, how to fix that.

**Comment by jsamr** [comment] 2020-09-24 10:25
@workhub90 As I have already stated, to help you out, I need at least the **HTML code** you are trying to render so that I can reproduce the issue on my end. And I don't really need the source code of react-native-render-html, we already have it on Github!

**Please**, read this https://stackoverflow.com/help/minimal-reproducible-example to grasp how communities of developers help out each other.

**Comment by workhub90** [comment] 2020-09-25 03:40
@jsamr thank you for replying. i has updated html tag for render detail article

**Comment by jsamr** [comment] 2020-09-25 10:44
@workhub90 When I render this html in a HTML component, I don't see the message you're referencing. 
But I noticed that this URL:

```html
https://stag.momsindonesia.com/info/kebijakan-privasi
```
This URL requires auth credentials, when you fail to provide them, you'll get this "no soup" message.

I am closing because I could not reproduce the issue with the provided HTML. With all respects, be advised that next time, I will ask you a full reproduction, as stated in the contribution guidelines, and close without notice if these are not provided. My time for volunteering is limited.

**Closed by jsamr** 2020-09-25 10:44 UTC
Labels: bug, is:missing reproduction, is:missing template
