### ISSUE TITLE
textSelectable not working

### ISSUE THREAD

**Issue by jjg77** [archriss/react-native-render-html#362] opened 2020-05-02 11:50 UTC
textSelectable prop does not work on Android or React Native Web.  My HTML component is part of a FlatList item, which may have something to do with the problem.

"react-native-render-html": "^4.2.0",

```
<HTML 
	            key={key}
	            html={body}
	            textSelectable={true} 
	            baseFontStyle={getStyle('bodyText', theme, largeText)}
	            onLinkPress={(event, href)=>{
	              //console.log('clicked: ', href)
	              WebBrowser.openBrowserAsync(href)
	            }}
	            tagsStyles={getTagsStyles(theme)}
	            classesStyles={getClassesStyles(theme)}
	            ignoredTags={['inline-block']}
	            alterData={(node) =>{
	              let { parent, data } = node
	              if(parent && parent.name === 'a' && /[^\u0000-\u00ff]/.test(data)){
	                return " "
	              }
	            }} 
	        />
```

**Comment by luiserd97** [comment] 2020-05-04 22:45
I have a similar problem, but my HTML is inside a View, and the textSelectable prop only work just after refreshing the page with ctrl + s in my code.

**Comment by jsamr** [comment] 2020-07-05 12:18
Possible duplicate of #193.

I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md). We need a full reproduction to help you out. Feel free to post a new compliant issue.

**Closed by jsamr** 2020-07-05 12:18 UTC
Labels: missing-template
