### ISSUE TITLE
React Native Web Warnings

### ISSUE THREAD

**Issue by jjg77** [archriss/react-native-render-html#356] opened 2020-04-15 13:58 UTC
Components works with React Native Web, but throws a bunch for warnings.  Some examples below:

```
Warning: React does not recognize the `baseFontStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `basefontstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Warning: Unknown event handler property `onLinkPress`. It will be ignored.
index.js:1 Warning: React does not recognize the `tagsStyles` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tagsstyles` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Warning: React does not recognize the `classesStyles` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `classesstyles` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

index.js:1 Warning: React does not recognize the `ignoredTags` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ignoredtags` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

index.js:1 Warning: React does not recognize the `alterData` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `alterdata` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Warning: Received `false` for a non-boolean attribute `debug`.

If you want to write it to the DOM, pass a string instead: debug="false" or debug={value.toString()}.
If you used to conditionally omit it with debug={condition && value}, pass debug={condition ? value : undefined} instead.

index.js:1 Warning: React does not recognize the `decodeEntities` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `decodeentities` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

index.js:1 Warning: React does not recognize the `emSize` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `emsize` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

```

**Comment by jsamr** [comment] 2020-07-04 18:47
I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), and it is impossible to investigate without a minimal reproduction. Feel free to post a new compliant issue.

**Closed by jsamr** 2020-07-04 18:47 UTC
