### ISSUE TITLE
After adding attribute to ignore in styles I got an Error

### ISSUE THREAD

**Issue by Sadhr** [archriss/react-native-render-html#337] opened 2020-01-28 13:03 UTC
After adding this attribute to ignoreStyles: 

`ignoredStyles={[
              "display",
              "width",
              "height",
              "font-family",
              "padding",
              "font-weight"
            ]}`

### Environment

Environment:
    React: 16.8.3
    React native: 0.58.0
    react-native-render-html: ^4.2.0

### Actual Behavior

![Screenshot_1580215600](https://user-images.githubusercontent.com/9772227/73266257-d58fcf80-41d6-11ea-9024-606a880ae009.png)

**Comment by jsamr** [comment] 2020-07-04 20:25
I'm closing because this issue does not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md). We would need a minimum working example and steps to reproduce to help you out here. Feel free to post a new compliant issue.

**Closed by jsamr** 2020-07-04 20:25 UTC
