### ISSUE TITLE
"inherit" styles should be removed or ignored during numeric conversion

### ISSUE THREAD

**Issue by vlaraort** [archriss/react-native-render-html#87] opened 2018-01-27 09:50 UTC
Hi! First of all thanks for the project. It's awesome!

I have encountered a problem. when I try to render a HTML with line-height css property non-numeric

`<a href="miurl.html#Crema de Pies y Codos" style="box-sizing: border-box; color: rgb(126, 126, 126); text-decoration-line: none; line-height: inherit;">text</a>`

Its generating an error, 

![image](https://user-images.githubusercontent.com/2410951/35470759-bdfd59e0-034f-11e8-8214-24bb2fee2204.png)

![image](https://user-images.githubusercontent.com/2410951/35470773-ea6a6b26-034f-11e8-82dc-2854bd110ead.png)

It's there any way to solve it? I am getting this HTML from a WYSWYG so I can't change the HTML 

I am using this versions:

    "react": "16.0.0-alpha.12",
    "react-native": "0.48.0",
    "react-native-render-html": "^3.2.0",

thanks!

**Comment by Exilz** [comment] 2018-02-05 08:28
Hi,
this isn't the first issue caused by `inherit`. This should be handled by the module and simply removed, it will be part of a future release once I or someone else can take a stab at it.

**Comment by Exilz** [comment] 2018-02-07 10:22
This should be fixed in the next release, don't bother opening a PR regarding this issue.

**Closed** 2018-02-08 10:34 UTC
Labels: bug
