### ISSUE TITLE
textAlign: 'justify' not working

### ISSUE THREAD

**Issue by rochapablo** [archriss/react-native-render-html#202] opened 2018-11-30 21:09 UTC
### Is this a bug report or a feature request?

bug report.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes, I did.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes, I did.

### Have you made sure that your issue hasn't already been reported/solved?

I'm sure of that.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I'm only testing on Android.

### Is the bug reproductible in a production environment (not a debug one)?

Never tried. But pretty sure that gets the same result.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

I'm gonna say no and keep going, hopping for the best.

### Environment

  Environment:
    React: 16.6.0-alpha.8af6728
    React native: 0.57.4
    react-native-render-html: 3.10.0

  Target Platform:
    Android (7.0)

### Steps to Reproduce

I'm just expecting for `textAlign:'justify'` work, so...

```
import HTML from 'react-native-render-html';

const styles = {
      a: {
        color: style.content.link.color,
        fontWeight: '300',
      },
      p: {
        color: this.props.data.color,
        fontSize: this.props.data.fontSize,
        lineHeight: this.props.data.lineHeight,
        marginBottom: 0,
        marginTop: 0,
        paddingBottom: 0,
        paddingTop: 0,
        textAlign: 'justify',
      },
    };

<HTML html={this.props.content} imagesMaxWidth={Dimensions.get('window').width}
                tagsStyles={styles}
                baseFontStyle={styles.p}
              />
``` 

### Expected Behavior

Expect justified paragraphs. But only works with textAlign `right` or `center`.  

### Actual Behavior

It gets align to `left` as default I guess.

### Reproducible Demo

Sorry, but I'm just hopping for the best.

**Comment by clytras** [comment] 2019-01-23 13:56
Maybe this is related to this RN spec:

> textAlign: enum('auto', 'left', 'right', 'center', 'justify')
> 
> Specifies text alignment. The value 'justify' is only supported on iOS and fallbacks to left on Android.

Android does not support `justify` for `textAlign`.

https://facebook.github.io/react-native/docs/text

**Comment by jariwalabhavesh** [comment] 2019-03-12 05:26
@clytras : Yes **justify** is not working in android. In ios, it just works fine. Is there any workaround for android?

**Comment by poison8** [comment] 2019-04-01 16:09
react-native 0.59  render-html 4.1.2 not working  justify for textAlign .

**Comment by successanil** [comment] 2019-06-11 03:05
> @clytras : Yes **justify** is not working in android. In ios, it just works fine. Is there any workaround for android?

Yes that feature is not supported natively by Android OS , thats why react native can't do it from outside but as a workaround you can use webview (kinda dirty solution) .

**Comment by GabrielePrestifilippo** [comment] 2019-09-04 14:31
As of now, from react-native 0.60, the `justify` works on android too (API >=26) https://facebook.github.io/react-native/docs/text#docsNav

**Comment by jsamr** [comment] 2020-07-05 14:08
I am closing because the issue is upstream (react native) and has been fixed since release 0.60.

**Closed by jsamr** 2020-07-05 14:08 UTC
Labels: bug

**Comment by noumantahir** [comment] 2022-01-26 19:11
@jsamr  Apparently I am facing this issue on RN 0.60+ and Android API 31, rendering with textAlign:'justify' not working as expected.. it works with regular `Text` component but not working with RenderHtml package... I did double check if prop is actually being passed to right tag as well.

<img width="983" alt="Screenshot 2022-01-27 at 12 06 24 AM" src="https://user-images.githubusercontent.com/6298342/151229843-8ee274d6-8f80-48c3-b02e-edfffda7d33a.png">

<img width="513" alt="Screenshot 2022-01-27 at 12 05 09 AM" src="https://user-images.githubusercontent.com/6298342/151229830-f9ab6121-f522-44e7-88f4-7f4888532e12.png">

Facing issue only on Android, iOS side words as expected.
<img width="530" alt="Screenshot 2022-01-27 at 12 08 52 AM" src="https://user-images.githubusercontent.com/6298342/151230242-19159de1-9951-404b-bf75-fe87bdb119b0.png">

**Comment by jsamr** [comment] 2022-01-26 20:50
>  it works with regular Text component but not working with RenderHtml package...

@noumantahir I suggest that you provide a full reproduction in a separate ticket, with the exact HTML snippet, library version and React Native version, and I will be happy to investigate and test on my machine! https://github.com/meliorence/react-native-render-html/issues/new/choose

**Comment by noumantahir** [comment] 2022-01-27 07:28
@jsamr apologies for inconvenience, I dug more deep today, apparently if we set `selectable` prop to `true`, the `textAlign:'justify'` stops working. That makes it an issue with react-native and not with render-html.

```
    <RenderHTML 
      source={{ html:`<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's  </p>` }}
      tagsStyles={{
        p:{textAlign:'justify'}
      }}
      defaultTextProps={{
        selectable:true
      }}
    />
```

**Comment by jsamr** [comment] 2022-01-27 11:35
@noumantahir No worries! It is yet another layout bug in React involving `Text`... that is worth mentioning in the FAQ page.

**Comment by dimmu123** [comment] 2022-12-09 22:43
> @jsamr apologies for inconvenience, I dug more deep today, apparently if we set `selectable` prop to `true`, the `textAlign:'justify'` stops working. That makes it an issue with react-native and not with render-html.
> 
> Sample code attached anyways, if we set selectable to false, the text will start justifying.
> 
> ```
>     <RenderHTML 
>       source={{ html:`<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's  </p>` }}
>       tagsStyles={{
>         p:{textAlign:'justify'}
>       }}
>       defaultTextProps={{
>         selectable:true
>       }}
>     />
> ```

This fixed my issue. Thanks!

**Comment by agunbuhori** [comment] 2023-02-27 14:36
In 2023, still not working to add 'textAlign: justify' on android. Please help

**Comment by longhaha1998** [comment] 2024-04-28 07:35
In 2024, still not working to add 'textAlign: justify' on android.

**Comment by muazasim-pixarsart** [comment] 2025-01-15 18:11
In 2025, still not working to add 'textAlign: justify' on android.
