### ISSUE TITLE
Iframe not working until <HTML /> is rendered within a <ScrollView />

### ISSUE THREAD

**Issue by pixelize** [archriss/react-native-render-html#271] opened 2019-07-09 09:31 UTC
### Is this a bug report or a feature request?

Bug

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platform

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment
  Environment:
    "react": "16.8.6",
    "react-native": "0.59.9",
   "react-native-render-html": "^4.1.2",

  Target Platform:
    Android (8.0)
    iOS (11)

### Steps to Reproduce

Just place an iframe in your html content

### Expected Behavior

The video should be visible

### Actual Behavior

The video is not displayed until you wrap a `<ScrollView />`.

### Reproducible Demo

https://snack.expo.io/@pixelize_/webview-bug

**Comment by Beissner** [comment] 2019-11-13 18:46
Any news on this? Anyone able to get videos to work?

**Comment by jsamr** [comment] 2020-07-05 13:59
@pixelize Because the iframe rendering highly depends on the WebView you are using, and react-native-webview is now a peer dependency, I suggest you try again with the latest RNWV version. I'm closing now, but you are free to reopen if you have reproduced the issue with latest webview version. In which case, please post a new snack!

**Closed by jsamr** 2020-07-05 13:59 UTC
Labels: bug
