### ISSUE TITLE
Global font properties

### ISSUE THREAD

**Issue by johncrisostomo** [archriss/react-native-render-html#25] opened 2017-10-05 08:48 UTC
This is perfect for what I need, thanks for the good work. The only problem I have is that aside from `baseFontSize`, there doesn't seem to be an `prop` that I can use to change the `color`, `fontFamily` and the other attributes for all the text. Targeting each element using the `tagsStyles` work, but I just need a global ('*') rule to make all the text fit in (look the same) with the rest of my application. 

Is there a workaround for this?

**Comment by Exilz** [comment] 2017-10-05 08:51
Hi,
no, there is no workaround for this at the time.

We just added support the the `baseFontSize` prop, but we need to improve it to support the full range of text styling attributes. That would be much better.

It shouldn’t be hard to implement, most of the work is already there. In the meantime, I’m afraid you’re gonna have to use `tagsStyle`… or open a PR :)

**Comment by johncrisostomo** [comment] 2017-10-05 09:09
@Exilz Hahaha, fair enough, thanks. Yes, I have started reading the source code. I'm checking out how easy it is to implement. If I have the time, I'll definitely submit a PR for this. Thank you again!

**Comment by Exilz** [comment] 2017-10-17 15:50
Hi @johncrisostomo,
I'm currently working on this feature right now as I found out in one of our apps that this is actually a very critical feature to add.

The problem is that with nested texts, if your lovely contributors feed you something like

```html
<strong><p>This is a text</p></strong>
```

instead of 

```html
<p><strong>This is a text</strong></p>
```

Your text won't be in bold if you supplied a `<p>` style in your `tagsStyles` prop.

This is because since the `<p>` is the deepest tag, its style will be the last to be applied.

The solution to this problem, rather than fiddling with the renderer and moving around the styles is this new `baseFontStyle` prop that would replace your typical `<p>` style.

[Here is the WIP commit on the development branch](https://github.com/archriss/react-native-render-html/commit/d03e69a4e00f286dfec45bc96e072551969906b3). I'd love it if you could take a look at it and tell me what you think.

**Comment by Exilz** [comment] 2017-10-19 13:44
This landed in `3.5.0-rc.1`. Since this release is quite important, testing would be appreciated !

**Comment by johncrisostomo** [comment] 2017-10-23 07:52
@Exilz Thanks so much for this! Sorry I have been busy the last few days, but will definitely test this out.

**Comment by Exilz** [comment] 2017-10-27 09:54
Looks like it's working properly. Please re-open an issue if it breaks something on your side.

**Closed by Exilz** 2017-10-27 09:54 UTC
Labels: review needed
