### ISSUE TITLE
Override Image resizeMode ?

### ISSUE THREAD

**Issue by cristianoccazinsp** [archriss/react-native-render-html#269] opened 2019-06-29 20:56 UTC
### Is this a bug report or a feature request?
Feature Request

Is it possible to override images resizeMode ? I've tried custom styles and renderersProps but neither reach the Image component.

**Comment by jsamr** [comment] 2020-07-05 10:24
Duplicate of #172, closing.

**Closed by jsamr** 2020-07-05 10:24 UTC
Labels: new feature
